// Auto-generated by data_prep/generate_data.py -- do not edit by hand.
// Source: How Raleigh Moves Walking, Biking and Transit Survey (Data + Comments exports).
window.SURVEY = {
  "meta": {
    "total": 1196,
    "q1Answered": 1178,
    "nNever": 747,
    "nLapsed": 122,
    "nNonrider": 869,
    "nRider": 309,
    "pctNonrider": 73.8,
    "pctNever": 63.4,
    "pctRider": 26.2
  },
  "q1": {
    "labels": [
      "Do not use the bus",
      "Used to, not in past 6 months",
      "Occasionally",
      "Weekly",
      "Daily"
    ],
    "counts": [
      747,
      122,
      172,
      68,
      69
    ]
  },
  "reasons": {
    "nonriders": {
      "labels": [
        "Schedule or frequency no longer works for me",
        "Safety concerns",
        "My travel needs changed",
        "Gained access to a car or other travel option",
        "The switch from free to fare-based service",
        "Other"
      ],
      "counts": [
        85,
        83,
        67,
        53,
        46,
        35
      ]
    },
    "lapsed": {
      "labels": [
        "Schedule or frequency no longer works for me",
        "My travel needs changed",
        "The switch from free to fare-based service",
        "Safety concerns",
        "Gained access to a car or other travel option",
        "Other"
      ],
      "counts": [
        44,
        40,
        32,
        25,
        24,
        20
      ]
    }
  },
  "importance": {
    "nonriders": [
      {
        "name": "Better sidewalks, crosswalks, or other infrastructure to safely reach bus stop",
        "n": 711,
        "mean": 4.17,
        "pctImportant": 79.0
      },
      {
        "name": "Better bus stop amenities - lighting at bus stops",
        "n": 717,
        "mean": 3.86,
        "pctImportant": 69.7
      },
      {
        "name": "More reliable services",
        "n": 734,
        "mean": 3.85,
        "pctImportant": 68.9
      },
      {
        "name": "Better bus stop amenities - shelters",
        "n": 728,
        "mean": 3.75,
        "pctImportant": 66.3
      },
      {
        "name": "More routes to new places",
        "n": 749,
        "mean": 3.74,
        "pctImportant": 67.7
      },
      {
        "name": "Better bus stop amenities - benches",
        "n": 720,
        "mean": 3.71,
        "pctImportant": 64.3
      },
      {
        "name": "More frequent service on existing routes",
        "n": 743,
        "mean": 3.68,
        "pctImportant": 63.5
      },
      {
        "name": "Improved trip planning applications",
        "n": 726,
        "mean": 3.54,
        "pctImportant": 56.9
      },
      {
        "name": "Additional park-and-ride facilities",
        "n": 709,
        "mean": 3.28,
        "pctImportant": 48.8
      },
      {
        "name": "Improved fare payment options",
        "n": 722,
        "mean": 3.27,
        "pctImportant": 45.0
      },
      {
        "name": "Better bus stop amenities - bike racks",
        "n": 710,
        "mean": 3.0,
        "pctImportant": 37.3
      }
    ],
    "riders": [
      {
        "name": "Better sidewalks, crosswalks, or other infrastructure to safely reach bus stop",
        "n": 286,
        "mean": 4.39,
        "pctImportant": 86.7
      },
      {
        "name": "More reliable services",
        "n": 287,
        "mean": 4.3,
        "pctImportant": 84.3
      },
      {
        "name": "More frequent service on existing routes",
        "n": 292,
        "mean": 4.23,
        "pctImportant": 82.9
      },
      {
        "name": "More routes to new places",
        "n": 288,
        "mean": 3.86,
        "pctImportant": 72.9
      },
      {
        "name": "Better bus stop amenities - benches",
        "n": 285,
        "mean": 3.84,
        "pctImportant": 67.4
      },
      {
        "name": "Better bus stop amenities - lighting at bus stops",
        "n": 286,
        "mean": 3.82,
        "pctImportant": 71.0
      },
      {
        "name": "Better bus stop amenities - shelters",
        "n": 288,
        "mean": 3.77,
        "pctImportant": 68.8
      },
      {
        "name": "Improved trip planning applications",
        "n": 284,
        "mean": 3.43,
        "pctImportant": 52.8
      },
      {
        "name": "Improved fare payment options",
        "n": 285,
        "mean": 3.16,
        "pctImportant": 40.7
      },
      {
        "name": "Better bus stop amenities - bike racks",
        "n": 281,
        "mean": 3.08,
        "pctImportant": 36.7
      },
      {
        "name": "Additional park-and-ride facilities",
        "n": 282,
        "mean": 2.99,
        "pctImportant": 37.9
      }
    ]
  },
  "fareKnowledge": {
    "nonriders": {
      "Yes, I know how": 167,
      "No, but assume it is similar": 295,
      "No, would like to learn": 156,
      "No, not interested": 117
    },
    "riders": {
      "Yes, I know how": 255,
      "No, but assume it is similar": 15,
      "No, would like to learn": 12,
      "No, not interested": 3
    }
  },
  "payment": {
    "nonriders": {
      "labels": [
        "The Umo app",
        "Cash",
        "A physical GoRaleigh card"
      ],
      "counts": [
        85,
        45,
        34
      ]
    },
    "riders": {
      "labels": [
        "The Umo app",
        "A physical GoRaleigh card",
        "Cash"
      ],
      "counts": [
        191,
        56,
        33
      ]
    }
  },
  "stopProximity": {
    "nonriders": {
      "Yes": 385,
      "No": 185,
      "Not sure": 75
    },
    "riders": {
      "Yes": 216,
      "No": 24,
      "Not sure": 6
    }
  },
  "openThemes": [
    {
      "question": "Q6: Circumstances to ride",
      "n": 271,
      "Payment / app": 2.6,
      "Safety / crime": 17.7,
      "Frequency / reliability": 22.5,
      "Car dependence": 22.5,
      "Routes / coverage": 20.3
    },
    {
      "question": "Q7: Change for +1 day/week",
      "n": 180,
      "Payment / app": 1.7,
      "Safety / crime": 20.6,
      "Frequency / reliability": 25.0,
      "Car dependence": 15.6,
      "Routes / coverage": 20.0
    },
    {
      "question": "Q8: First word or phrase",
      "n": 221,
      "Payment / app": 0.0,
      "Safety / crime": 13.6,
      "Frequency / reliability": 4.1,
      "Car dependence": 13.6,
      "Routes / coverage": 1.8
    },
    {
      "question": "Q9: Versus other systems",
      "n": 179,
      "Payment / app": 22.9,
      "Safety / crime": 11.2,
      "Frequency / reliability": 34.1,
      "Car dependence": 9.5,
      "Routes / coverage": 24.6
    }
  ],
  "demoCoverage": [
    {
      "field": "Age",
      "n": 363,
      "pct": 30.4
    },
    {
      "field": "Race",
      "n": 331,
      "pct": 27.7
    },
    {
      "field": "Disability",
      "n": 329,
      "pct": 27.5
    },
    {
      "field": "Income",
      "n": 308,
      "pct": 25.8
    },
    {
      "field": "Gender",
      "n": 342,
      "pct": 28.6
    },
    {
      "field": "Rent/own",
      "n": 325,
      "pct": 27.2
    },
    {
      "field": "Employment",
      "n": 329,
      "pct": 27.5
    },
    {
      "field": "Education",
      "n": 237,
      "pct": 19.8
    }
  ],
  "gender": {
    "nFemale": 172,
    "nMale": 153,
    "importance": [
      {
        "improvement": "Better bus stop amenities - lighting at bus stops",
        "female": 4.02,
        "male": 3.52,
        "gap": 0.5
      },
      {
        "improvement": "Better bus stop amenities - benches",
        "female": 3.87,
        "male": 3.54,
        "gap": 0.33
      },
      {
        "improvement": "Better sidewalks, crosswalks, or other infrastructure to safely reach bus stop",
        "female": 4.41,
        "male": 4.08,
        "gap": 0.33
      },
      {
        "improvement": "Additional park-and-ride facilities",
        "female": 3.21,
        "male": 2.91,
        "gap": 0.3
      },
      {
        "improvement": "Improved trip planning applications",
        "female": 3.53,
        "male": 3.31,
        "gap": 0.22
      },
      {
        "improvement": "Better bus stop amenities - bike racks",
        "female": 3.06,
        "male": 2.84,
        "gap": 0.22
      },
      {
        "improvement": "More routes to new places",
        "female": 3.96,
        "male": 3.77,
        "gap": 0.19
      },
      {
        "improvement": "Better bus stop amenities - shelters",
        "female": 3.77,
        "male": 3.58,
        "gap": 0.19
      },
      {
        "improvement": "More reliable services",
        "female": 4.03,
        "male": 3.87,
        "gap": 0.16
      },
      {
        "improvement": "Improved fare payment options",
        "female": 3.13,
        "male": 3.01,
        "gap": 0.12
      },
      {
        "improvement": "More frequent service on existing routes",
        "female": 3.93,
        "male": 3.88,
        "gap": 0.05
      }
    ],
    "fareKnowledge": {
      "female": {
        "Yes, I know how": 41.2,
        "No, but assume it is similar": 31.8,
        "No, would like to learn": 18.2,
        "No, not interested": 8.8
      },
      "male": {
        "Yes, I know how": 51.0,
        "No, but assume it is similar": 31.8,
        "No, would like to learn": 9.9,
        "No, not interested": 7.3
      }
    },
    "riderStatus": {
      "female": {
        "Rider": 28.1,
        "Non-rider (lapsed)": 12.3,
        "Non-rider (never)": 59.6
      },
      "male": {
        "Rider": 29.6,
        "Non-rider (lapsed)": 10.5,
        "Non-rider (never)": 59.9
      }
    },
    "safety": {
      "female": {
        "n": 117,
        "mentions": 37,
        "pct": 31.6
      },
      "male": {
        "n": 100,
        "mentions": 23,
        "pct": 23.0
      }
    },
    "reasons": {
      "female": {
        "Schedule or frequency no longer works for me": 38.9,
        "My travel needs changed": 37.0,
        "The switch from free to fare-based service": 24.1,
        "Safety concerns": 20.4,
        "Other": 16.7,
        "Gained access to a car or other travel option": 16.7
      },
      "male": {
        "Schedule or frequency no longer works for me": 39.6,
        "My travel needs changed": 35.8,
        "Safety concerns": 28.3,
        "Gained access to a car or other travel option": 20.8,
        "Other": 20.8,
        "The switch from free to fare-based service": 13.2
      },
      "n_female_answers": 54,
      "n_male_answers": 53
    }
  },
  "income": {
    "fareSwitch": [
      {
        "bucket": "Under $50k",
        "n": 43,
        "pct": 14.0
      },
      {
        "bucket": "$50k-$99k",
        "n": 90,
        "pct": 8.9
      },
      {
        "bucket": "$100k+",
        "n": 175,
        "pct": 3.4
      }
    ]
  },
  "tenure": {
    "ownPct": 33.9,
    "ownN": 183,
    "rentPct": 53.2,
    "rentN": 126
  },
  "comments": {
    "summary": [
      {
        "id": 396284,
        "label": "3b. Improvements to the fare system",
        "total": 363,
        "public": 305,
        "upvotes": 515,
        "pctUpvoted": 50.8
      },
      {
        "id": 396287,
        "label": "6. Circumstances more likely to ride",
        "total": 426,
        "public": 388,
        "upvotes": 494,
        "pctUpvoted": 42.8
      },
      {
        "id": 396289,
        "label": "7. Change to ride one more day/week",
        "total": 291,
        "public": 260,
        "upvotes": 165,
        "pctUpvoted": 10.4
      },
      {
        "id": 396290,
        "label": "8. First word or phrase about the bus",
        "total": 333,
        "public": 313,
        "upvotes": 129,
        "pctUpvoted": 12.8
      },
      {
        "id": 396291,
        "label": "9. Versus bus systems elsewhere",
        "total": 284,
        "public": 253,
        "upvotes": 152,
        "pctUpvoted": 20.2
      },
      {
        "id": 396292,
        "label": "Walk/bike 1. Crossing-street experience",
        "total": 414,
        "public": 387,
        "upvotes": 469,
        "pctUpvoted": 25.6
      },
      {
        "id": 396293,
        "label": "Walk/bike 2. Easier/harder crossing spots",
        "total": 307,
        "public": 289,
        "upvotes": 212,
        "pctUpvoted": 17.3
      },
      {
        "id": 396294,
        "label": "Walk/bike 3. Confusing intersections",
        "total": 180,
        "public": 168,
        "upvotes": 114,
        "pctUpvoted": 18.5
      },
      {
        "id": 396306,
        "label": "Walk/bike 5. What feels comfortable",
        "total": 331,
        "public": 311,
        "upvotes": 183,
        "pctUpvoted": 10.0
      },
      {
        "id": 396506,
        "label": "Walk/bike 6. What feels stressful",
        "total": 304,
        "public": 282,
        "upvotes": 174,
        "pctUpvoted": 11.7
      },
      {
        "id": 396507,
        "label": "Walk/bike 9. Why not walk or bike",
        "total": 285,
        "public": 265,
        "upvotes": 188,
        "pctUpvoted": 7.9
      },
      {
        "id": 396511,
        "label": "11. Improve walk/bike to transit stops",
        "total": 160,
        "public": 149,
        "upvotes": 128,
        "pctUpvoted": 8.1
      },
      {
        "id": 396516,
        "label": "12a. Disability / mobility / sensory needs",
        "total": 56,
        "public": 51,
        "upvotes": 43,
        "pctUpvoted": 15.7
      },
      {
        "id": 396191,
        "label": "1a. Reasons for stopping riding",
        "total": 46,
        "public": 0,
        "upvotes": 0,
        "pctUpvoted": null
      },
      {
        "id": 396307,
        "label": "Walk/bike 7. Safety concerns changing routes",
        "total": 252,
        "public": 0,
        "upvotes": 0,
        "pctUpvoted": null
      },
      {
        "id": 396310,
        "label": "Walk/bike 8. Easier to figure out",
        "total": 68,
        "public": 0,
        "upvotes": 0,
        "pctUpvoted": null
      },
      {
        "id": 396518,
        "label": "13. Make walking/biking more appealing",
        "total": 47,
        "public": 0,
        "upvotes": 0,
        "pctUpvoted": null
      },
      {
        "id": 396333,
        "label": "5. Map pins of weekly trips",
        "total": 617,
        "public": 608,
        "upvotes": 16,
        "pctUpvoted": 2.5
      }
    ],
    "topQuotes": {
      "396284": [
        {
          "upvotes": 63,
          "text": "Tap phone to pay"
        },
        {
          "upvotes": 38,
          "text": "Higher frequency to reduce the need to plan my trip before every ride, routes that don't always have to go through Downtown, but pick up in neighborhoods, cleanliness on the bus and at the bus stop, more pedestrian safety elements at the bus stop and corresponding road and intersection, improved public safety."
        },
        {
          "upvotes": 36,
          "text": "Tap to Pay/Open Payment"
        },
        {
          "upvotes": 20,
          "text": "Tap to pay and a modern ticket system would be amazing on top of increasing express routes."
        }
      ],
      "396287": [
        {
          "upvotes": 99,
          "text": "If it didn't literally take 4 times longer to get anywhere than by car."
        },
        {
          "upvotes": 56,
          "text": "Airport service that doesn't require changing at the stupid transit center out there. Is the airport not a transit center? why not send all the busses there and let us change to a durham bus or head into the airport for work"
        },
        {
          "upvotes": 42,
          "text": "The main bus station needs to be cleaned up.  I was there two weeks ago when there was a drug bust with 6 police vehicles that came in from both directions and arrested someone 4 seats away from me.  I am now avoiding it like the plague."
        },
        {
          "upvotes": 24,
          "text": "More Frequent Buses, Better Behavior on the buses, people are eating, drinking including alcohol, yelling, loud music, blocking aisle with big suitcases and carts, the buses are dirty, their is not behavior enforcement on the buses, making it hard for those trying to go to work."
        }
      ],
      "396289": [
        {
          "upvotes": 56,
          "text": "Higher frequency, more safety, and more dedicated bus lanes"
        },
        {
          "upvotes": 28,
          "text": "Speed and reliability"
        },
        {
          "upvotes": 22,
          "text": "Direct routes to where I want to go. I do not want to go through the downtown bust station."
        },
        {
          "upvotes": 11,
          "text": "Continue the 30-minute departure interval of the DRX from Raleigh to Durham until 10am."
        }
      ],
      "396290": [
        {
          "upvotes": 47,
          "text": "time-consuming"
        },
        {
          "upvotes": 20,
          "text": "Complicated schedules and safety"
        },
        {
          "upvotes": 10,
          "text": "The behavior and cleanliness of the buses has significantly decayed the last 3 years. Moore Square all is dirty, people are drinking, smoking marijuana and I have seen security walk right by these people. I have even seen several women walking in just underwear. The needs to be enforcement of basic behavior rules  there and on the bus. This is not done. Supervisors are not doing their job when ask"
        },
        {
          "upvotes": 4,
          "text": "Dirty"
        }
      ],
      "396291": [
        {
          "upvotes": 36,
          "text": "\"Tap to Pay\" system that I have used in other major city transit services"
        },
        {
          "upvotes": 26,
          "text": "Tap to pay, easy to navigate, live/accurate schedule in Google maps, frequently available (no big deal about missing a bus), many routes. Lots of people taking the bus so it feels safe."
        },
        {
          "upvotes": 11,
          "text": "Tap to pay meant no barriers to just spontaneously deciding to use it. Electric buses were modern and clean."
        },
        {
          "upvotes": 8,
          "text": "Umo App is hard to understand. Most cities have tap to ride systems."
        }
      ],
      "396292": [
        {
          "upvotes": 81,
          "text": "Drivers do not respect pedestrians."
        },
        {
          "upvotes": 61,
          "text": "lack of sidewalks"
        },
        {
          "upvotes": 56,
          "text": "Most drivers in Raleigh do not respect the \"no turn on red\" signs, which makes crossing the street extremely dangerous, especially with little kids."
        },
        {
          "upvotes": 41,
          "text": "not enough cross walks or sidewalks on many streets, including New Bern Ave"
        }
      ],
      "396293": [
        {
          "upvotes": 50,
          "text": "IRONWORKS. Dear god. Atlantic Avenue / Whittaker Mill"
        },
        {
          "upvotes": 39,
          "text": "Glenwood.  Any part of this road except for downtown is a pedestrian nightmare."
        },
        {
          "upvotes": 25,
          "text": "Peace at Person St is very dangerous. Crossing Wake Forest Rd north of Franklin is very dangerous (cars go SO fast). Above all else Atlantic Avenue at Whitaker Mill is an accident waiting to happen. I cannot believe the City allowed developers to build Iron Works and did not force them to build a safe pedestrian crossing across Atlantic to connect to the stuff on Whitaker Mill. People are often ru"
        },
        {
          "upvotes": 12,
          "text": "easier if there is a cross walk."
        }
      ],
      "396294": [
        {
          "upvotes": 25,
          "text": "The part along Glenwood where the sidewalk disappears because of the train tracks"
        },
        {
          "upvotes": 22,
          "text": "need crosswalks and sidewalks on New Bern Ave"
        },
        {
          "upvotes": 19,
          "text": "Atlantic Ave at Whitaker Mill, New Bern at King Charles (lights are timed so you have to run across 1/2 the street, wait in the median, and run across the other half)."
        },
        {
          "upvotes": 8,
          "text": "Whittaker Mill / Atlantic Avenue."
        }
      ],
      "396306": [
        {
          "upvotes": 80,
          "text": "Having separation from cars.  We need sidewalks and protected bike lanes."
        },
        {
          "upvotes": 24,
          "text": "dedicated bike lanes...ideally protected from traffic\nSidewalks that are clean and consistent, not littered with scooters,"
        },
        {
          "upvotes": 16,
          "text": "For Biking I love the greenway because it is completely separate from cars. I also appreciate the separated bike lanes that have a grassy median between bikes and cars."
        },
        {
          "upvotes": 12,
          "text": "For biking, having separation from vehicle lanes or being in a low-traffic area.  For walking, having a complete sidewalk that means I don't have to walk through someone's yard or along a ditch."
        }
      ],
      "396506": [
        {
          "upvotes": 57,
          "text": "lack of sidewalks or having to share the road with cars as biker (no separate bike lane)"
        },
        {
          "upvotes": 39,
          "text": "Conflicts at intersections with cars, distracted drivers"
        },
        {
          "upvotes": 25,
          "text": "no sidewalks, poor lighting"
        },
        {
          "upvotes": 6,
          "text": "It is uncomfortable to walk or bike on streets with high speed limits (over 35 mph) or where right turns on red is allowed."
        }
      ],
      "396507": [
        {
          "upvotes": 63,
          "text": "no sidewalks"
        },
        {
          "upvotes": 39,
          "text": "distance and/or weather"
        },
        {
          "upvotes": 37,
          "text": "Many roads are required to be on to get to certain destinations, especially in the Midtown or North Raleigh area. Those roads act like impassable rivers for a pedestrian or bicyclist, so the only option is to drive, or take a bus that requires an exchange which can extend travel time by 4 times the amount of time it would take to drive, if you are able to drive."
        },
        {
          "upvotes": 9,
          "text": "Fear of having to cross any road. Drivers cannot be trusted to yield when supposed to"
        }
      ],
      "396511": [
        {
          "upvotes": 48,
          "text": "Sidewalks"
        },
        {
          "upvotes": 31,
          "text": "Greenway connections, lighting and mid block crossings. It's impossible to take the Route 3 anymore because you can't get across Raleigh Blvd because people drive 100 mph on that street."
        },
        {
          "upvotes": 24,
          "text": "street trees! lighting! sidewalks"
        },
        {
          "upvotes": 15,
          "text": "ADA-compliant sidewalk and/or separated bike lane leading up to the transit stops"
        }
      ],
      "396516": [
        {
          "upvotes": 14,
          "text": "Cars are so loud, so big, so fast, so dangerous."
        },
        {
          "upvotes": 13,
          "text": "need sidewalks and ramps"
        },
        {
          "upvotes": 8,
          "text": "Deaf and hard of hearing need to be able to see the area around them as well as signs, lights, and have a clear view of cars approaching. Sidewalks are often overgrown , which hides signs and lights and parts of the walkway."
        },
        {
          "upvotes": 4,
          "text": "Uterine cancer survivor, so I need reasonable access to restrooms."
        }
      ],
      "396191": [],
      "396307": [],
      "396310": [],
      "396518": [],
      "396333": [
        {
          "upvotes": 2,
          "text": "I usually travel from SE Raleigh off S. New Hope Rd to the downtown Raleigh area or Wake Forest Rd (Costco, Wegmans area)"
        },
        {
          "upvotes": 1,
          "text": "library"
        },
        {
          "upvotes": 1,
          "text": "Transfer Food Hall"
        },
        {
          "upvotes": 1,
          "text": "beer!"
        }
      ]
    },
    "aggregate": {
      "totalComments": 4764,
      "publicComments": 4029,
      "privateComments": 735,
      "totalUpvotes": 2982,
      "meanSentiment": -0.116,
      "profanity": 8,
      "tags": {
        "Tap to Pay": 11,
        "Protected Bike Lanes": 6,
        "Poor Lighting": 12,
        "Lack of Sidewalks": 25,
        "Lack of Bike Lanes": 8
      },
      "maxUpvote": 99
    }
  }
};
